### PR TITLE
implement `missingRecordHandler`

### PR DESCRIPTION
**Pull request by freakinruben**
solves #18 

What do you think of this implementation?

### CODE REVIEW

**Comment by glenjamin** [comment]
Looks broadly sensible to me, just needs the lint warnings fixing 🙂

**Comment by freakinruben** [comment]
Done. Let me know if you would like it implemented somewhere else or differently

**Comment by glenjamin** [comment]
I've just spotted that the withFilter function needs to pass the new option along too.

If you add that in I can merge & release - if not I'll probably sort it myself this evening

**Comment by glenjamin** [comment]
Ok, that's published as `v0.6.0` - thanks for the contribution!

**Comment by freakinruben** [comment]
You're fast! Thanks

**Pull request merged**
