### PR TITLE
Upgraded dependencies

### PR DESCRIPTION
**Pull request by pekkis**
Hey man! Pekkis from Finland here.

Firstly, thanks for your great work. Been using transit-immutable-js along the last couple of years - am a big fan, great stuff, very important (forgive the Trump talk).

A couple of problems have arisen, though.

Firstly, Immutable.js doesn't seem to be immutable once more, so I've made the jump to the 4.x versions. Transit-immutable-js failed there, so I fixed those errors. It seems that v4 records don't have a `toMap` anymore, so I had to change that behavior to throw. There might very well be a better way to handle that, but this behavior seemed ok to me at this point so I went with that.

Secondly, your repo seems to be a bit stale. Are you still alive, figuratively? Do you need help maintaining this? I want this to work, I need this to work, and am willing to help. Otherwise I'll just have to fork anyways. I merged the stack-contributing pull request here as well, and upgraded all dependencies (not sure that they 100% work yet, but it's just a start). What I'll do next, I think, is to rewrite this to modern ES and upgrade the dev / build stack completely.

Cheers, man!

### CODE REVIEW

**Comment by glenjamin** [comment]
Hello

Yep, i’m still here - I didn’t think there was much to do, which is why I hadn’t touched anything for a while.

Not sure why I forgot about the Stack PR though.

I’m happy to take all the upgrades and fixes for v4, as it’s still only an RC then i’d ideally like to support both versions at the same time

I’m less keen on “upgrading” to a “modern ES stack” unless there’s particular benefits to specific changes - otherwise it’s just change for change’s sake. Updating the node versions on CI makes sense though

I’ll have a look over this PR later this weekend

**Comment by pekkis** [comment]
OK, good that you're still active, and let's continue later. I'll be flying to Indonesia for a week tomorrow so no hurry. I'll check this again when I'm back.

**Comment by 10xLaCroixDrinker** [comment]
@glenjamin is this PR dead in the water?

**Comment by glenjamin** [comment]
This PR has 3 or 4 different changes in it.

I’m also not keen on forcing users to use v4 while it’s still marked as an RC - so I would prefer to maintain backwards compatibility with v3.

I’ll try and make some time to incorporate these changes soon

**Comment by 10xLaCroixDrinker** [comment]
I'll put together a PR to support both

**Comment by 10xLaCroixDrinker** [comment]
opened #50

**Pull request closed without merging**
